### ISSUE TITLE
Add a wiki page tutorial about positioning the canvas

### ISSUE THREAD

**Issue by toolness** [processing/p5.js#1333]
Currently, the default canvas created by p5 doesn't have any style applied to it, but @iamjessklein and I aren't sure if this is optimal behavior for beginners. We may be wrong, but it's probably more likely that they'd like their canvas centered on the page?

Of course, we don't want to disrupt the styling of more experienced users, so I wonder if we could do something like the following when p5 **global mode** initializes itself:
1. Check to see if the p5 canvas is the only visible element on the page.
2. If it is, inject the following CSS into the page:
   
   ``` css
       html, body {
         height: 100%;
       }
   
       body {
         margin: 0;
         display: flex;
         justify-content: center;
         align-items: center;
       }
   ```

Thoughts? If this is a bad idea, I guess we could just move the above CSS onto a wiki page or something... Or explicitly add a p5 method called `centerCanvasOnPage()` maybe? Hmm.
