### ISSUE TITLE
Error font cannot be defined

### ISSUE THREAD

**Issue by akhilanadimpalli** [processing/p5.js#1842]
hai
i have an error while writing the below program.

```
var font;
function preload()
{
  font=loadFont('Avenir-Next-LT-Pro-Demi_5188');
}

function setup() {
  createCanvas(800,300);
  background(51);
  textFont="30px Arial";;  
  textSize(128);
  fill(255);
  noStroke();
  text('Akhila',100,200);
  var points= font.textToPoints('Akhila',100,200);
  console.log(points);
  for(var i=0;i<points.length;i++)
  {
    var pt=points[i];
    stroke(0,255,0);
    strokeWeight(4);
    point(pt.x, pt.y);
  }
 
}

function draw() {
  
}
```

i downloaded the font style and kept it at p5 file .
please help me that how to define a font style in javascript in p5 .

**Comment by dhowe** [comment]
Does the file have a file extension? Avenir-Next-LT-Pro-Demi_5188.ttf or Avenir-Next-LT-Pro-Demi_5188.otf ?

**Comment by akhilanadimpalli** [comment]
hi 
ya it have an extension  Avenir-Next-LT-Pro-Demi_5188.otf  but it is not working.

in which folder i should keep this...

**Comment by feedzh** [comment]
Hello,

You can load webfont with css file and then use it in p5

css:
```css
@font-face {
font-family: 'Avenir Next LT Pro Demi';
font-style: normal;
font-weight: normal;
src: local('Avenir Next LT Pro Demi'), url('AvenirNextLTPro-Demi.woff') format('woff');
}
```

javascript:
```javascript
function draw() {
    clear();
    textSize(36);
    textFont("Avenir Next LT Pro Demi");
    text('Akhila',100,200);
}
```
